import SideNav from '../components/dashboard/side-nav';
import '../globals.css';
import { onest } from '../ui/fonts';
import { Bars3Icon } from '@heroicons/react/24/outline';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@300,301,400,401,500,501,700,701,900,901&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${onest.className}`}>
        <div className="sm:flex">
          <div className="hidden md:block">
            <SideNav />
          </div>
          <div className="sm:hidden m-3 flex justify-end">
            <Bars3Icon className="w-5 h-5 text-black" />
          </div>
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
